name: 'Fides Secret Scanner'
description: 'Fides - helping you keep secrets secret'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      run: sudo apt-get update && sudo apt-get install -y python3.9
      shell: bash

    - name: Install Fides Requirements
      run: pip install -r requirements.txt
      shell: bash

    - name: paths
      run: ls
      shell: bash

    - name: paths
      run: |
        cd ..
        ls
      shell: bash

    - name: paths
      run: |
        cd ..
        cd ..
        ls
      shell: bash

    - name: Run Fides
      run: python ../../fides/run.py
      shell: bash