name: 'Fides Secret Scanner'
description: 'Fides - helping you keep secrets secret'
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Check out Fides code
      uses: actions/checkout@v2
      with:
        repository: joocer/fides
        path: fides

    - name: paths
      run: |
        ls
        cd ..
        ls
        cd ..
        ls
      shell: bash

    - name: Install Fides Requirements
      run: pip install -r requirements.txt
      shell: bash

    - name: Run Fides
      run: python ../fides/run.py
      shell: bash